"""Stage 5: emit diffusion-pipe anima.toml (FULL finetune) for the Anima model.

Full finetune = NO [adapter] block. Tag-only captions (caption_mode='tags').
llm_adapter_lr=0 freezes the Qwen3 LLM adapter. Paths are absolute Vast (Linux) paths.
"""
from pathlib import Path

import common

LOG = common.setup_logging()


def write_anima_toml(out_path, base_dir, project_name, dit_file, vae_file, qwen_file,
                     epochs, lr, optimizer, warmup_steps, save_every_n_epochs,
                     checkpoint_every_n_minutes, llm_adapter_lr,
                     tag_dropout_percent, caption_dropout_percent, steps_per_print=100):
    base = base_dir.rstrip("/")
    out_dir = f"{base}/outputs/{project_name}"
    dataset_toml = f"{base}/outputs/{project_name}_dataset_config.toml"
    models = f"{base}/models"
    toml = f"""# diffusion-pipe — Anima FULL finetune (realism domain shift). Generated by stage 5.
output_dir = '{out_dir}'
dataset = '{dataset_toml}'

epochs = {epochs}
micro_batch_size_per_gpu = 1
pipeline_stages = 1
gradient_accumulation_steps = 1
gradient_clipping = 1.0
steps_per_print = {steps_per_print}
warmup_steps = {warmup_steps}
activation_checkpointing = true

# Eval disabled for run 1 (no eval set). Preview epoch checkpoints in ComfyUI instead.
eval_before_first_step = false
eval_every_n_epochs = 100000

save_every_n_epochs = {save_every_n_epochs}
checkpoint_every_n_minutes = {checkpoint_every_n_minutes}
save_dtype = 'bfloat16'

[model]
type = 'anima'
transformer_path = '{models}/{dit_file}'
vae_path = '{models}/{vae_file}'
qwen_path = '{models}/{qwen_file}'
dtype = 'bfloat16'
llm_adapter_lr = {llm_adapter_lr}
cache_text_embeddings = false
shuffle_tags = true
tag_delimiter = ', '
shuffle_keep_first_n = 1
tag_dropout_percent = {tag_dropout_percent}
caption_dropout_percent = {caption_dropout_percent}
caption_mode = 'tags'
timestep_sample_method = 'logit_normal'

# NOTE: no [adapter] block => full finetune (not LoRA).

[optimizer]
type = '{optimizer}'
lr = {lr}
betas = [0.9, 0.99]
weight_decay = 0.01
eps = 1e-8

[monitoring]
enable_wandb = false
"""
    Path(out_path).write_text(toml, encoding="utf-8")


def main():
    cfg = common.load_config()
    f = cfg["finetune"]
    out = Path(cfg["paths"]["outputs"])
    out.mkdir(parents=True, exist_ok=True)
    toml_path = out / f"{f['project_name']}_train_config.toml"
    write_anima_toml(
        toml_path,
        base_dir=f["base_dir"], project_name=f["project_name"],
        dit_file=f["dit_file"], vae_file=f["vae_file"], qwen_file=f["qwen_file"],
        epochs=f["epochs"], lr=f["lr"], optimizer=f["optimizer"], warmup_steps=f["warmup_steps"],
        save_every_n_epochs=f["save_every_n_epochs"],
        checkpoint_every_n_minutes=f["checkpoint_every_n_minutes"],
        llm_adapter_lr=f["llm_adapter_lr"],
        tag_dropout_percent=f["tag_dropout_percent"],
        caption_dropout_percent=f["caption_dropout_percent"],
        steps_per_print=f.get("steps_per_print", 100),
    )
    LOG.info("Stage 5 done. anima.toml -> %s", toml_path)


if __name__ == "__main__":
    main()
